[[cenm-1-0]]
identifier = "cenm-1-0-concepts-and-overview"
name = "Concepts and Overview"
weight = 10

[[cenm-1-0]]
identifier = "cenm-1-0-configuration"
name = "Configuration"
weight = 200

[[cenm-1-0]]
identifier = "cenm-1-0-enm-releases"
name = "ENM Releases"
weight = 70

[[cenm-1-0]]
identifier = "cenm-1-0-operations"
name = "Operations"
weight = 110

[[cenm-1-0]]
identifier = "cenm-1-0-private-networks"
name = "Private Networks"
weight = 290

[[cenm-1-0]]
identifier = "cenm-1-0-public-key-infrastructure"
name = "Public Key Infrastructure"
weight = 310

[[cenm-1-0]]
identifier = "cenm-1-0-tools-and-utilities"
name = "Tools & Utilities"
weight = 260

[[cenm-1-1]]
identifier = "cenm-1-1-cenm-releases"
name = "CENM Releases"
weight = 70

[[cenm-1-1]]
identifier = "cenm-1-1-concepts-and-overview"
name = "Concepts and Overview"
weight = 10

[[cenm-1-1]]
identifier = "cenm-1-1-configuration"
name = "Configuration"
weight = 210

[[cenm-1-1]]
identifier = "cenm-1-1-operations"
name = "Operations"
weight = 110

[[cenm-1-1]]
identifier = "cenm-1-1-public-key-infrastructure"
name = "Public Key Infrastructure"
weight = 300

[[cenm-1-1]]
identifier = "cenm-1-1-tools-and-utilities"
name = "Tools & Utilities"
weight = 270

[[cenm-1-2]]
identifier = "cenm-1-2-cenm-releases"
name = "CENM Releases"
weight = 70

[[cenm-1-2]]
identifier = "cenm-1-2-concepts-and-overview"
name = "Concepts and Overview"
weight = 10

[[cenm-1-2]]
identifier = "cenm-1-2-configuration"
name = "Configuration"
weight = 210

[[cenm-1-2]]
identifier = "cenm-1-2-operations"
name = "Operations"
weight = 110

[[cenm-1-2]]
identifier = "cenm-1-2-public-key-infrastructure"
name = "Public Key Infrastructure"
weight = 300

[[cenm-1-2]]
identifier = "cenm-1-2-signing-plugin-samples"
name = "Signing Plugin Samples"
weight = 330

[[cenm-1-2]]
identifier = "cenm-1-2-tools-and-utilities"
name = "Tools & Utilities"
weight = 270

[[corda-enterprise-3-3]]
identifier = "corda-enterprise-3-3-corda-enterprise"
name = "Corda Enterprise"
weight = 10

[[corda-enterprise-3-3]]
identifier = "corda-enterprise-3-3-development"
name = "Development"
weight = 100

[[corda-enterprise-3-3]]
identifier = "corda-enterprise-3-3-operations"
name = "Operations"
weight = 210

[[corda-enterprise-3-3]]
identifier = "corda-enterprise-3-3-other-docs"
parent = "corda-enterprise-3-3-quickstart"
name = "Other docs"
weight = 1000

[[corda-enterprise-4-0]]
identifier = "corda-enterprise-4-0-corda-enterprise"
name = "Corda Enterprise"
weight = 90

[[corda-enterprise-4-0]]
identifier = "corda-enterprise-4-0-corda-network"
name = "Corda Network"
weight = 350

[[corda-enterprise-4-0]]
identifier = "corda-enterprise-4-0-development"
name = "Development"
weight = 170

[[corda-enterprise-4-0]]
identifier = "corda-enterprise-4-0-operations"
name = "Operations"
weight = 280

[[corda-enterprise-4-1]]
identifier = "corda-enterprise-4-1-corda-network"
name = "Corda Network"
weight = 260

[[corda-enterprise-4-1]]
identifier = "corda-enterprise-4-1-development"
name = "Development"
weight = 70

[[corda-enterprise-4-1]]
identifier = "corda-enterprise-4-1-operations"
name = "Operations"
weight = 180

[[corda-enterprise-4-1]]
identifier = "corda-enterprise-4-1-participate"
name = "Participate"
weight = 270

[[corda-enterprise-4-2]]
identifier = "corda-enterprise-4-2-corda-enterprise"
name = "Corda Enterprise"
weight = 90

[[corda-enterprise-4-2]]
identifier = "corda-enterprise-4-2-corda-network"
name = "Corda Network"
weight = 380

[[corda-enterprise-4-2]]
identifier = "corda-enterprise-4-2-development"
name = "Development"
weight = 180

[[corda-enterprise-4-2]]
identifier = "corda-enterprise-4-2-miscellaneous"
name = "Miscellaneous"
weight = 390

[[corda-enterprise-4-2]]
identifier = "corda-enterprise-4-2-operations"
name = "Operations"
weight = 280

[[corda-enterprise-4-3-1]]
identifier = "corda-enterprise-4-3-1-corda-api"
name = "Corda API"
weight = 290

[[corda-enterprise-4-3-1]]
identifier = "corda-enterprise-4-3-1-corda-enterprise"
name = "Corda Enterprise"
weight = 80

[[corda-enterprise-4-3-1]]
identifier = "corda-enterprise-4-3-1-corda-network"
name = "Corda Network"
weight = 510

[[corda-enterprise-4-3-1]]
identifier = "corda-enterprise-4-3-1-development"
name = "Development"
weight = 170

[[corda-enterprise-4-3-1]]
identifier = "corda-enterprise-4-3-1-miscellaneous"
name = "Miscellaneous"
weight = 520

[[corda-enterprise-4-3-1]]
identifier = "corda-enterprise-4-3-1-operations"
name = "Operations"
weight = 430

[[corda-enterprise-4-4]]
identifier = "corda-enterprise-4-4-concepts-and-overview"
parent = "corda-enterprise-4-4-cenm"
name = "Concepts and Overview"
weight = 1000

[[corda-enterprise-4-4]]
identifier = "corda-enterprise-4-4-configuration"
parent = "corda-enterprise-4-4-config-identity-manager-parameters"
name = "Configuration"
weight = 1000

[[corda-enterprise-4-4]]
identifier = "corda-enterprise-4-4-corda-nodes"
name = "Corda Nodes"
weight = 210

[[corda-enterprise-4-4]]
identifier = "corda-enterprise-4-4-cordapps"
name = "CorDapps"
weight = 70

[[corda-enterprise-4-4]]
identifier = "corda-enterprise-4-4-miscellaneous"
name = "Miscellaneous"
weight = 390

[[corda-enterprise-4-4]]
identifier = "corda-enterprise-4-4-upgrading-and-tools"
name = "Upgrading and Tools"
weight = 10

[[corda-os-4-0]]
identifier = "corda-os-4-0-corda-network"
name = "Corda Network"
weight = 230

[[corda-os-4-0]]
identifier = "corda-os-4-0-design-docs"
name = "Design docs"
weight = 280

[[corda-os-4-0]]
identifier = "corda-os-4-0-development"
name = "Development"
weight = 40

[[corda-os-4-0]]
identifier = "corda-os-4-0-operations"
name = "Operations"
weight = 150

[[corda-os-4-0]]
identifier = "corda-os-4-0-participate"
name = "Participate"
weight = 240

[[corda-os-4-1]]
identifier = "corda-os-4-1-corda-network"
name = "Corda Network"
weight = 260

[[corda-os-4-1]]
identifier = "corda-os-4-1-development"
name = "Development"
weight = 70

[[corda-os-4-1]]
identifier = "corda-os-4-1-operations"
name = "Operations"
weight = 180

[[corda-os-4-1]]
identifier = "corda-os-4-1-participate"
name = "Participate"
weight = 270

[[corda-os-4-3]]
identifier = "corda-os-4-3-corda-api"
name = "Corda API"
weight = 180

[[corda-os-4-3]]
identifier = "corda-os-4-3-corda-network"
name = "Corda Network"
weight = 400

[[corda-os-4-3]]
identifier = "corda-os-4-3-development"
name = "Development"
weight = 60

[[corda-os-4-3]]
identifier = "corda-os-4-3-operations"
name = "Operations"
weight = 320

[[corda-os-4-3]]
identifier = "corda-os-4-3-participate"
name = "Participate"
weight = 410

[[corda-os-4-4]]
identifier = "corda-os-4-4-corda-api"
name = "Corda API"
weight = 180

[[corda-os-4-4]]
identifier = "corda-os-4-4-corda-network"
name = "Corda Network"
weight = 400

[[corda-os-4-4]]
identifier = "corda-os-4-4-development"
name = "Development"
weight = 60

[[corda-os-4-4]]
identifier = "corda-os-4-4-operations"
name = "Operations"
weight = 320

[[corda-os-4-4]]
identifier = "corda-os-4-4-participate"
name = "Participate"
weight = 410

